Warehouse/RecOutletWarehouse/RecOutletWarehouse/Controllers/ItemManagementController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RecOutletWarehouse.Models;
using RecOutletWarehouse.Models.ItemManagement;
using RecOutletWarehouse.Utilities;


namespace RecOutletWarehouse.Controllers
{
    public class ItemManagementController : Controller
    {

        RecreationOutletContext entityDb = new RecreationOutletContext();
        //
        // GET: /ItemMangement/

        public class ItemDeptCatSubcatViewModel {
            public Department department { get; set; }
            public Category category { get; set; }
            public SubCategory subcat { get; set; }
        }

        //New view model that incorporates the Entity Framework models
        public class newItemDeptCatSubcatViewModel
        {
            public ITEM_DEPARTMENT department { get; set; }
            public ITEM_CATEGORY category { get; set; }
            public ITEM_SUBCATEGORY subcat { get; set; }
        }

        public class allItemDeptCatSubcatViewModel
        {
            public List<ITEM_DEPARTMENT> departments { get; set; }
            public List<ITEM_CATEGORY> categorys { get; set; }
            public List<ITEM_SUBCATEGORY> subcats { get; set; }
        }

        public ActionResult CreateNewItem()
        {
            try
            {
                //DataFetcherSetter db = new DataFetcherSetter();
                //List<SubCategory> testList = db.SearchSubcategoriesByName("a");

                return View();
            }
            catch (Exception ex)
            {
                WarehouseUtilities.LogError(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        public ActionResult CreateNewItem(Item item, string labelRedirect = "")
        {
            try
            {
                DataFetcherSetter db = new DataFetcherSetter();

                item.CreatedDate = DateTime.Now.Date;
                item.CreatedBy = 1; //TODO: Associate with logged-in user   
                item.TaxRate = 5; //TODO: A lot of things :)
                if (item.UPC == null)
                    item.UPC = 0; //TODO: Fix this
                if (item.restrictedAge == null)
                    item.restrictedAge = 0; //TODO: Fix this
                item = db.ConvertNamesToIDs(item);

                //CUSTOM VALIDATION FOLLOWS
                //Check if Vendor exists or if too many vendors were returned
                if (item.Vendor == "0")
                {
                    ModelState.AddModelError("Vendor", "That vendor doesn't exist.");
                }
                if (item.Vendor == "-1")
                {
                    ModelState.AddModelError("Vendor", "Multiple vendors have that name.");
                }
                //Check if Product Line exists or if too many were returned
                if (item.ProductLine == "0")
                {
                    ModelState.AddModelError("ProductLine", "That product line doesn't exist OR is not "
                                           + "associated with the specified vendor.");
                }
                if (item.ProductLine == "-1")
                {
                    ModelState.AddModelError("ProductLine", "Multiple product lines have that name and vendor.");
                }

                //Check if Department exists or if too many were returned
                if (item.Department == "0")
                {
                    ModelState.AddModelError("Department", "That department doesn't exist.");
                }
                if (item.Department == "-1")
                {
                    ModelState.AddModelError("Department", "Multiple departments have that name.");
                }

                //Check if Category exists or if too many were returned
                if (item.Category == "0")
                {
                    ModelState.AddModelError("Category", "That category doesn't exist.");
                }
                if (item.Category == "-1")
                {
                    ModelState.AddModelError("Category", "Multiple categories have that name.");
                }

                //Check if Subcategory exists or if too many were returned
                if (item.Subcategory == "0")
                {
                    ModelState.AddModelError("Subcategory", "That subcategory doesn't exist.");
                }
                if (item.Subcategory == "-1")
                {
                    ModelState.AddModelError("Subcategory", "Multiple subcategories have that name.");
                }

                //CUSTOM VALIDATION ENDS

                item.ItemId = db.GetNextItemForDeptCatSubcat(Convert.ToByte(item.Department),
                                                            Convert.ToByte(item.Category),
                                                            Convert.ToInt16(item.Subcategory));
                item.RecRPC = WarehouseUtilities.GenerateRPC(item);

                if (ModelState.IsValid)
                {
                    db.AddNewItem(item);
                    ViewBag.ItemSuccessfulInsert = item.ItemName + " " + item.RecRPC + ".";
                    if (labelRedirect == "Create Item and Print Labels")
                    {
                        return RedirectToAction("PrintLabels", new { id = item.RecRPC });
                    }

                    return View(new Item());
                }

                return View(item);
            }
            catch (Exception ex)
            {
                WarehouseUtilities.LogError(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult PrintLabels(long? id)
        {
            try
            {
                ViewBag.RPC = id.ToString();
                return View();
            }
            catch (Exception ex)
            {
                WarehouseUtilities.LogError(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        public ActionResult PrintLabels(LabelPrinting labelModel)
        {
            try
            {
                DataFetcherSetter db = new DataFetcherSetter();
                Item tempItem = new Item();
                if (!ModelState.IsValid)
                {
                    return View(labelModel);
                }
                if (labelModel.RPC != "")
                {
                    tempItem = db.GetItemForRPC(Convert.ToInt64(labelModel.RPC));
                }
                //TODO: add logic that will search for an item given a UPC or item info and NOT an RPC

                if (labelModel.LabelType == "RPC")
                {
                    WarehouseUtilities.PrintRPCLabel(tempItem, labelModel.LabelQty);
                }

                if (labelModel.LabelType == "UPC")
                {
                    //TODO: print a UPC label given labelModel's information
                }

                return View();
            }
            catch (Exception ex)
            {
                WarehouseUtilities.LogError(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult addNewDeptCatSubcat()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                WarehouseUtilities.LogError(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        public ActionResult addNewDeptCatSubcat(newItemDeptCatSubcatViewModel model, string submitButton)
        {
            try
            {
                DataFetcherSetter db = new DataFetcherSetter();
                if (submitButton == "Department")
                {
                    ViewBag.activeTab = "Department";
                    //TODO: check for duplicates
                    if (!ModelState.IsValid)
                    {
                        return View(model);
                    }
                    //db.AddDepartment(model.department);
                    entityDb.ITEM_DEPARTMENT.Add(model.department);
                    entityDb.SaveChanges();

                    ViewBag.deptSuccess = "Department \"" + model.department.DepartmentName + "\" successfully added.";

                    return View(new newItemDeptCatSubcatViewModel());
                }

                if (submitButton == "Category")
                {
                    ViewBag.activeTab = "Category";
                    //TODO: check for duplicates
                    if (!ModelState.IsValid)
                    {
                        return View(model);
                    }
                    //db.AddCategory(model.category);
                    entityDb.ITEM_CATEGORY.Add(model.category);
                    entityDb.SaveChanges();

                    ViewBag.catSuccess = "Category \"" + model.category.CategoryName + "\" successfully added.";

                    return View(new newItemDeptCatSubcatViewModel());
                }

                if (submitButton == "Subcategory")
                {
                    ViewBag.activeTab = "Subcategory";
                    //TODO: check for duplicates
                    if (!ModelState.IsValid)
                    {
                        return View(model);
                    }
                    //db.AddSubcategory(model.subcat);

                    entityDb.ITEM_SUBCATEGORY.Add(model.subcat);
                    entityDb.SaveChanges();


Warehouse/RecOutletWarehouse/RecOutletWarehouse/Views/ItemManagement/EditItemCharacteristics.cshtml
@model RecOutletWarehouse.Controllers.ItemManagementController.newItemDeptCatSubcatViewModel
@{
    ViewBag.Title = "EditItemCharacteristics";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Edit Item Characteristics</h2>

@if (ViewBag.editButton == "category")
{
    using (Html.BeginForm())
    {
        <fieldset>
            <legend>Edit Category</legend>
            <div class="editor-label">
                <label>Category ID: @Html.DisplayFor(x => x.category.CategoryID)</label>
            </div>
            <hr />
            <div class="editor-label">
                <label>Category Name</label>
            </div>
            <div class="editor-field">
                @Html.EditorFor(x => x.category.CategoryName)
            </div>
            <div class="editor-label">
                <label>Category Description</label>
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(x => x.category.CategoryDescription)
            </div>
            <button name="editButton" type="submit" value="category" class="button">Save</button>
            @Html.HiddenFor(x => x.category.CategoryID)
        </fieldset>
    }
}
else if (ViewBag.editButton == "subcategory")
{
    using (Html.BeginForm())
    {
        <fieldset>
            <legend>Edit Subcategory</legend>
            <label>Subcategory ID: @Html.DisplayFor(x => x.subcat.SubcategoryID)</label>
            <hr />
            <div class="editor-label">
                <label>Subcategory Name</label>
            </div>
            <div class="editor-field">
                @Html.EditorFor(x => x.subcat.SubcategoryName)
            </div>
            <button name="editButton" type="submit" value="subcategory" class="button">Save</button>
            @Html.HiddenFor(x => x.subcat.SubcategoryID)
        </fieldset>
    }
}
else if (ViewBag.editButton == "department")
{
    using (Html.BeginForm())
    {
        <fieldset>
            <legend>Edit Department</legend>
            <label>Department ID: @Html.DisplayFor(x => x.department.DepartmentID)</label>
            <br />
            <div class="editor-label">
                <label>Department Name</label>
            </div>
            <div class="editor-field">
                @Html.EditorFor(x => x.department.DepartmentName)
            </div>
            <div class="editor-label">
                <label>Department Description</label>
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(x => x.department.DepartmentDescription)
            </div>
            <button name="editButton" type="submit" value="department" class="button">Save</button>
            @Html.HiddenFor(x => x.department.DepartmentID)
        </fieldset>
    }
}

Warehouse/RecOutletWarehouse/RecOutletWarehouse/Views/ItemManagement/ItemCharacteristics.cshtml
@using System.Web.Optimization;
@model RecOutletWarehouse.Controllers.ItemManagementController.allItemDeptCatSubcatViewModel
@{
    ViewBag.Title = "ItemCharacteristics";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Item Characteristics</h2>

@section tabnavigation{
    <ul class="nav clearfix">
        <li>@Html.ActionLink("Create New Item","CreateNewItem")</li>
        <li>@Html.ActionLink("Print Item Labels","PrintLabels")</li>
        <li class="active">@Html.ActionLink("Item Characteristics","ItemCharacteristics")</li>
    </ul> 
}

<div class="item-char-container">
    <div class="item-char-outter">
        <h3 class="item-char">Categories</h3>
        <hr />
        <div class="item-char">
            @foreach (var item in Model.categorys)
            {
                <div class="item-char-row">
                    <div class="item-char-list1"><p class="item-char">@item.CategoryID</p></div>
                    <div class="item-char-list2"><p class="item-char">@item.CategoryName</p></div>
                    <div class="item-char-list3"><input type="button" value="Edit" class="button"
                                                            onclick="location.href='@Url.Action("EditItemCharacteristics", "ItemManagement", 
                                                                        new {id = item.CategoryID, editButton = "category"})'" /></div>
                </div>
            }
        </div>
    </div>
    <div class="item-char-outter">
        <h3 class="item-char">Subcategories</h3>
        <hr />
        <div class="item-char">
            @foreach (var item in Model.subcats)
            {
                <div class="item-char-row">
                    <div class="item-char-list1"><p class="item-char">@item.SubcategoryID</p></div>
                    <div class="item-char-list2"><p class="item-char">@item.SubcategoryName</p></div>
                    <div class="item-char-list3"><input type="button" value="Edit" class="button"
                                                            onclick="location.href='@Url.Action("EditItemCharacteristics", "ItemManagement", 
                                                                        new {id = item.SubcategoryID, editButton = "subcategory"})'" /></div>
                </div>
            }
        </div>
    </div>
    <div class="item-char-outter">
        <h3 class="item-char">Departments</h3>
        <hr />
        <div class="item-char">
            @foreach (var item in Model.departments)
            {
                <div class="item-char-row">
                    <div class="item-char-list1"><p class="item-char">@item.DepartmentID</p></div>
                    <div class="item-char-list2"><p class="item-char">@item.DepartmentName</p></div>
                    <div class="item-char-list3"><input type="button" value="Edit" class="button"
                                                            onclick="location.href='@Url.Action("EditItemCharacteristics", "ItemManagement",
                                                                        new {id = item.DepartmentID, editButton = "department"})'" /></div>
                </div>
            }
        </div>
    </div>
</div>
<center>
<input type="button" onclick="JavaScript:newPopup('@Url.Action("addNewDeptCatSubcat", "ItemManagement")    ');" class="button" value="Add a new Department, Category, and/or Subcategory" />
</center>

<script type="text/javascript">
    // Popup window code
    function newPopup(url) {
        popupWindow = window.open(
            url, 'popUpWindow', 'height=700,width=800,left=10,top=10,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no,status=yes')
    }
</script>

Warehouse/RecOutletWarehouse/RecOutletWarehouse/Views/ItemManagement/PrintLabels.cshtml
@model RecOutletWarehouse.Models.ItemManagement.LabelPrinting

@{
    ViewBag.Title = "PrintLabels";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@section tabnavigation{
    <ul class="nav clearfix">
        <li>@Html.ActionLink("Create New Item","CreateNewItem")</li>
        <li class="active">@Html.ActionLink("Print Item Labels","PrintLabels")</li>
        <li>@Html.ActionLink("Item Characteristics","ItemCharacteristics")</li>
    </ul>  
}

<h2>Print RPC or UPC Labels</h2>

@if(ViewBag.ItemSuccessfulInsert != null){
<ul>
    <li class="successful-insert">@ViewBag.ItemSuccessfulInsert</li>
</ul>
}

@using(Html.BeginForm()){
    <fieldset>
        <legend>Item information</legend>
        <p>If you know the RPC or UPC number of the item, please enter it below:</p>
        <table>
            <tr>
                <td>Item RPC: </td>
                <td>@Html.TextBoxFor(item => item.RPC, new {@class = "LabelRPC",  @Value = ViewBag.RPC })</td>
                <td>&nbsp Item UPC: </td>
                <td>@Html.TextBoxFor(item => item.UPC, new { @class = "LabelRPC" })</td>
            </tr>
        </table>
        <hr />
        <p>If you don't know the RPC/UPC, you can search for the item using the following fields:</p>
        <table>
            <tr>
                <td>Item Name:</td>
                <td>@Html.TextBoxFor(item => item.ItemName)</td>
            </tr>
        </table>

        <p>Type of labels to print: @Html.RadioButtonFor(model => model.LabelType, "RPC", new { Checked = "checked"}) RPC @Html.RadioButtonFor(model => model.LabelType, "UPC") UPC</p>
        <p>Number of labels to print: @Html.TextBoxFor(model => model.LabelQty, new { @class = "LabelPrintCount" }) @Html.ValidationMessageFor(model => model.LabelQty)</p>

        <input type="submit" value="Print Labels" onclick="submit()" class="button"/>
    
    </fieldset>
}

Warehouse/RecOutletWarehouse/RecOutletWarehouse/Views/ItemManagement/addNewDeptCatSubcat.cshtml
@model RecOutletWarehouse.Controllers.ItemManagementController.newItemDeptCatSubcatViewModel

@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<head>
    <title>Add a new Department, Category, or Subcategory</title>
    <script>
        $(function () {
            $("#tabs").tabs();
        });
    </script>

    @if (ViewBag.activeTab == "Category") {
        <script>
            $(document).ready(function () {
                $("#tabs").tabs({ active: 1 });
            });
        </script>
    }

    @if (ViewBag.activeTab == "Subcategory") {
        <script>
            $(document).ready(function () {
                $("#tabs").tabs({ active: 2 });
            });
        </script>
    }

</head>

<body>
    <h2>What would you like to add?</h2>
    <div id="tabs">
        <ul class ="nav clearfix">
            <li><a href="#tabs-1">New Department</a></li>
            <li><a href="#tabs-2">New Category</a></li>                          
            <li><a href="#tabs-3">New Subcategory</a></li>
        </ul>
    
        <div id="tabs-1">
            @if (ViewBag.deptSuccess != null) {
                <p class="successful-insert">@ViewBag.deptSuccess</p>
            }
            @using (Html.BeginForm()) {
                <table>
                    <tr>
                        <td>
                            Department Number:
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.department.DepartmentID)
                            @Html.ValidationMessageFor(model => model.department.DepartmentID)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Department Name:
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.department.DepartmentName)
                            @Html.ValidationMessageFor(model => model.department.DepartmentName)
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <button name="submitButton" value ="Department">Create Department</button>
                        </td>
                    </tr>
                </table>
            }
        </div>

        <div id="tabs-2">
            @if (ViewBag.catSuccess != null) {
                <p class="successful-insert">@ViewBag.catSuccess</p>
            }
            @using (Html.BeginForm()) {
                <table>
                    <tr>
                        <td>
                            Category Name: 
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.category.CategoryName)
                            @Html.ValidationMessageFor(model => model.category.CategoryName)
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <button name="submitButton" value ="Category">Create Category</button>
                        </td>
                    </tr>
                </table>
            }
        </div>

        <div id="tabs-3">
            @if (ViewBag.subcatSuccess != null) {
                <p class="successful-insert">@ViewBag.subcatSuccess</p>
            }
            @using (Html.BeginForm()) {
                <table>
                    <tr>
                        <td>
                            Subcategory Name:
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.subcat.SubcategoryName)
                            @Html.ValidationMessageFor(model => model.subcat.SubcategoryName)
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <button name="submitButton" value ="Subcategory">Create Subcategory</button>
                        </td>
                    </tr>
                </table>
            }
        </div>
    </div> <!--.tabs-->

    <a href="JavaScript:window.close()">Close Window</a>

</body>