Warehouse/RecOutletWarehouse/RecOutletWarehouse/Models/PURCHASE_ORDER.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RecOutletWarehouse.Models
{
    public partial class PURCHASE_ORDER
    {
        public PURCHASE_ORDER()
        {
            this.PO_LINEITEM = new List<PO_LINEITEM>();
        }

        [Required]
        public long POID { get; set; }

        [Required]
        public short VendorID { get; set; }

        [Required]
        public short POCreatedBy { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}",
               ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> POOrderDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}",
               ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> POEstimatedShipDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}",
               ApplyFormatInEditMode = true)]
        public System.DateTime POCreatedDate { get; set; }

        public string POFreightCost { get; set; }
        public string POTerms { get; set; }
        public string POComments { get; set; }
        public Nullable<int> ShippingID { get; set; }
        public Nullable<System.DateTime> POCancelIfNotReceivedBy { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ICollection<PO_LINEITEM> PO_LINEITEM { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}

Warehouse/RecOutletWarehouse/RecOutletWarehouse/Controllers/PurchaseOrderController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RecOutletWarehouse.Models;
using RecOutletWarehouse.Models.PurchaseOrder;
using RecOutletWarehouse.Models.VendorManagement;
using RecOutletWarehouse.Models.ItemManagement;
using RecOutletWarehouse.Utilities;
using System.Data.Entity;

namespace RecOutletWarehouse.Controllers
{
    public class PurchaseOrderController : Controller
    {
        RecreationOutletContext entityDb = new RecreationOutletContext();
        public int BrowsePageSize = 25; // The number of results we want to show on each BrowseVendor page

        //ViewModel: PurchaseOrderAndLineItem
        //A ViewModel allows you to access data from different models 
        //(often database tables) in a single view

        /// <summary>
        /// The ViewModel that allows retrieval and insertion of data from and into
        /// the PurchaseOrder and POLineItem models within a single form
        /// </summary>
        /// <author>Tyler M.</author>
        public class PurchaseOrderCreationViewModel
        {
            public PurchaseOrderCreationViewModel() {
                VendorItems = new List<VendorItemsViewModel>();
            }
            public PURCHASE_ORDER PO { get; set; }
            public List<PO_LINEITEM> AddedLineItems { get; set; }
            public List<VendorItemsViewModel> VendorItems { get; set; }
            //public  ItemToAdd { get; set; }
            public List<string> ItemNames { get; set; }
            public List<int> VendorIds { get; set; }
            public String tempPOID { get; set; }
        }

        public class VendorItemsViewModel {
            public ITEM VendorItem { get; set; }
            public short QtyToOrder { get; set; }
            public decimal ItemCostEach { get; set; }
        }

        public class PurchaseOrderSearchViewModel
        {
            public List<PURCHASE_ORDER> POs { get; set; }
            public PagingInfo PagingInfo { get; set; }
            public string search { get; set; }
        }

        //public class PO_LineItemList {
        //    public PURCHASE_ORDER PO { get; set; }
        //    public List<PO_LINEITEM> LineItems { get; set; }
        //}

        //
        // GET: /PurchaseOrder/

        public ActionResult Index()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                WarehouseUtilities.LogError(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet]
        public ActionResult CreateNewPO()
        {
            try
            {

                //DataFetcherSetter db = new DataFetcherSetter();
                //int nextPO = db.getLastPONumForDate(DateTime.Now.Date);

                int nextPO = Utilities.WarehouseUtilities.getPODateCount();

                ViewBag.PO = createPOForForm(nextPO);

                return View();
            }
            catch (Exception ex)
            {
                WarehouseUtilities.LogError(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        /// <summary>
        /// Creates a purchase order with basic information
        /// </summary>
        /// <author>Tyler M.</author>
        /// <param name="POVM">The ViewModel to store PO information</param>
        /// <returns>A redirect to AddPOLineItem</returns>
        [HttpPost]
        public ActionResult CreateNewPO(PurchaseOrderCreationViewModel POVM)
        {
            try
            {
                DataFetcherSetter db = new DataFetcherSetter();

                ViewBag.PO = POVM.PO.POID;

                //TODO: Move the character replacement logic to a
                //tools class and enhance its functionality
                string POtoInt = POVM.tempPOID;
                POtoInt = POtoInt.Replace("-", string.Empty);

                int convertedPO = Convert.ToInt32(POtoInt);

                POVM.PO.POID = convertedPO;

                //find the vendor ID for the provided vendor name
                short vendorId = Convert.ToInt16(db.GetVendorIdForVendorName(POVM.PO.VENDOR.VendorName));

                POVM.PO.VENDOR = entityDb.VENDORs.Single(x => x.VendorName == POVM.PO.VENDOR.VendorName);

                POVM.PO.POCreatedDate = DateTime.Now;

                //CUSTOM VALIDATION FOLLOWS
                //if (db.RetrievePObyPOID(Convert.ToInt64(convertedPO)).PurchaseOrderId != null)
                //{
                //    ModelState.AddModelError("PO.PurchaseOrderId", "That PO Number already exists.");
                //}
                //if (vendorId == 0)
                //{
                //    ModelState.AddModelError("PO.Vendor", "That Vendor isn't in the database. Please add vendor information.");
                //}
                //else if (vendorId == -1)
                //{
                //    ModelState.AddModelError("PO.Vendor", "Please be more specific. TODO: better error message");
                //}

                //if (POVM.PO.OrderDate < DateTime.Now.Date)
                //{
                //    ModelState.AddModelError("PO.OrderDate", "That date has passed");
                //}
                //if (POVM.PO.EstShipDate < POVM.PO.OrderDate)
                //{
                //    ModelState.AddModelError("PO.EstShipDate", "The estimated ship date cannot occur before the order date");
                //}

                //CUSTOM VALIDATION ENDS

                POVM.PO.EMPLOYEE = entityDb.EMPLOYEEs.SingleOrDefault(x => x.EmployeeId == 1);
                //if (!ModelState.IsValid)
                //{
                //    return View(POVM);
                //}
                //else
                //{
                    //db.CreateNewPurchaseOrder(convertedPO,
                    //    vendorId, POVM.PO.CreatedBy,
                    //    POVM.PO.OrderDate, POVM.PO.EstShipDate,
                    //    POVM.PO.FreightCost, POVM.PO.Terms,
                    //    POVM.PO.Comments); //TODO: Associate the employeeID with this

                    entityDb.PURCHASE_ORDER.Add(POVM.PO);
                    entityDb.SaveChanges();

                    return RedirectToAction("AddPOLineItem", new { id = convertedPO });
                //}
            }
            catch (Exception ex)
            {
                WarehouseUtilities.LogError(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        /// <summary>
        /// Provides the form into which LineItems are entered for a particular PO
        /// (indicated by the id variable)
        /// </summary>
        /// <author>Tyler M.</author>
        /// <param name="id">The PO ID for which information is displayed and entered</param>
        /// <returns>The AddPOLineItem View, supplemented with general PO information</returns>
        public ActionResult AddPOLineItem(int id = 0)
        {
            try
            {
                // List<Item> items = db.SearchItemsByName("AS Laptop 17 B3250");
                PurchaseOrderCreationViewModel POVM = new PurchaseOrderCreationViewModel();
                POVM.PO = entityDb.PURCHASE_ORDER.Find(id);
                POVM.AddedLineItems = entityDb.PO_LINEITEM.Where(p => p.PURCHASE_ORDER.POID == POVM.PO.POID).ToList();
                List<VendorItemsViewModel> VIVMList = new List<VendorItemsViewModel>();
                List<ITEM> items = entityDb.ITEMs.Where(i => i.PRODUCT_LINE.VendorID == POVM.PO.VENDOR.VendorID).ToList();
                foreach (var item in items) {
                    VIVMList.Add(new VendorItemsViewModel{
                        VendorItem = item
                    });
                }

                ViewBag.TotalPOCost = String.Format("{0:$0.00}", POVM.AddedLineItems.Sum(x => x.WholesaleCost * x.QtyOrdered));

                POVM.VendorItems = VIVMList;

                return View(POVM);
            }
            catch (Exception ex)
            {
                WarehouseUtilities.LogError(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        /// <summary>
        /// Commits the POLineItems to the database with the provided POID
        /// </summary>
        /// <author>Tyler M.</author>
        /// <param name="POVM">The ViewModel that will store the POLineItems</param>
        /// <param name="id">The Purchase Order ID that these line items are associated with</param>
        /// <returns>A redirect to POSummary</returns>
        /// POST: PurchaseOrder/AddPOLineItem
        [HttpPost]
        public ActionResult AddPOLineItem(PurchaseOrderCreationViewModel POVM)
        {
            try
            {
                return View();
                //DataFetcherSetter db = new DataFetcherSetter();

                ////POVM.PO = db.RetrievePObyPOID(Convert.ToInt64(id));
                //string POtoInt = id;
                //POtoInt = POtoInt.Replace("-", string.Empty);

                //int convertedPO = Convert.ToInt32(POtoInt);
                //decimal totalCost = Convert.ToDecimal(POVM.PO.POFreightCost);

                ////TODO: Move the character replacement logic to a
                ////tools class and enhance its functionality

                //foreach (var item in POVM.LineItems)
                //{
                //    if (item.RecRPC != 0 && item.WholesaleCost != 0 && item.QtyOrdered != 0)
                //    { //do not attempt to add empty list items
                //      //db.NewPOLineItemForPO(convertedPO, item.RecRPC, item.WholesaleCost,

Warehouse/RecOutletWarehouse/RecOutletWarehouse/Views/PurchaseOrder/AddPOLineItem.cshtml
@model RecOutletWarehouse.Controllers.PurchaseOrderController.PurchaseOrderCreationViewModel

@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<head>
    <title>Add Items to Purchase Order</title>
    <script>
        function doStuff() {
            var nameElement = document.getElementById("someInput");
            var theName = nameElement.value;
            document.getElementById("someDiv").innerHTML += theName;
        }
    </script>
</head>

<h2>Add Items to Purchase Order</h2>
<fieldset>
    <legend>Purchase Order General Information</legend>
    <table>
        <tr>
            <td>PO #:</td>
            <td>@Html.DisplayFor(model => model.PO.POID)</td>
            <td>Vendor:</td>
            <td>@Html.DisplayFor(model => model.PO.VENDOR.VendorName, new { id = "vendor" })</td>
        </tr>
        <tr>
            <td>PO ordered on:</td>
            <td>@Html.DisplayFor(model => model.PO.POOrderDate)</td>
            <td>PO estimated ship date: </td>
            <td>@Html.DisplayFor(model => model.PO.POEstimatedShipDate)</td>
        </tr>
    </table>
</fieldset>

<h3>Items currently on this purchase order</h3>
<div id ="currentLines">
    @{ Html.RenderPartial("POLineItemListPart", Model.AddedLineItems); }
</div>

<h3>Add new items to this purchase order</h3>
<table>
    <tr class="leftjust">
        <th>Item Name</th>
        <th>Vendor Item</th>
        <th>Add Qty</th>
        <th>Cost Each</th>
    </tr>
    @for (int i = 0; i < Model.VendorItems.Count; i++) {
        <tr>
            @using (Ajax.BeginForm("addItemToLineItems", new AjaxOptions { UpdateTargetId = "currentLines" })) {
                @* THE FOLLOWING FIELD USES AN EDITORFOR TEMPLATE, DO NOT MODIFY IN THIS VIEW *@
                @Html.EditorFor(model => Model.VendorItems[i])
                <td>
                    <input type="hidden" name="poid" value="@Model.PO.POID") />
                    <input type="hidden" name="num" value="@(i)" />
                    <input type="submit" value="Add to PO" class="button" />
                </td>
            }
        </tr>
    }
    
</table>
<hr />
<center>
<input type="button" onclick="location.href='@Url.Action("SearchPO", "PurchaseOrder")'" class="button" value="Finish" />
</center>

Warehouse/RecOutletWarehouse/RecOutletWarehouse/Views/PurchaseOrder/EditPO.cshtml
@model RecOutletWarehouse.Models.PURCHASE_ORDER
@{
    ViewBag.Title = "EditPO";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>EditPO</h2>
<div class="edit-po-container">
    <div class="edit-po">
    @using (Html.BeginForm(null, null, FormMethod.Post))
    {
        <fieldset>
            <legend>Edit PO @Html.DisplayFor(x => x.POID)</legend>
            <div class="editor-label">
                <label>Order Date</label>
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(x => x.POOrderDate, new { id = "order-date", @class = "datepicker", 
                        @Value = String.Format("{0:MM/dd/yyyy}", Model.POOrderDate) })
            </div>
            <div class="editor-label">
                <label>Estimated Shipping Date</label>
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(x => x.POEstimatedShipDate, new { id = "shipping-date", @class = "datepicker", 
                        @Value = String.Format("{0:MM/dd/yyyy}", Model.POEstimatedShipDate) })
            </div>
            <div class="editor-label">
                <label>Freight Cost</label>
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(x => x.POFreightCost)
            </div>
            <div class="editor-label">
                <label>Comments</label>
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(x => x.POComments)
            </div>
            <div class="editor-label">
                <label>PO Terms</label>
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(x => x.POTerms)
            </div>
            @Html.HiddenFor(x => x.POID)
            @Html.HiddenFor(x => x.VendorID)
            @Html.HiddenFor(x => x.VENDOR)
            @Html.HiddenFor(x => x.POCreatedBy)
            @Html.HiddenFor(x => x.POCreatedDate)
            @Html.HiddenFor(x => x.ShippingID)
            @Html.HiddenFor(x => x.POCancelIfNotReceivedBy)
            @Html.HiddenFor(x => x.EMPLOYEE)
            @Html.HiddenFor(x => x.PO_LINEITEM)
            <input type="submit" value="Save" class="button" />
            <input type="button" value="Cancel" class="button-cancel" 
                onclick="location.href='@Url.Action("SearchPO", "PurchaseOrder", 
                                        new {id = Model.POID})'"/>
        </fieldset>
    }
    </div>
    <div class="display-line-items">
        <div class="center-text line-item-area">
            <table class="potable" id="potable">
                <thead>
                    <tr>
                        <th>Vendor ID</th>
                        <th>Item Name</th>
                        <th>Qty</th>
                        <th>Item Cost</th>
                        <th>Total Cost</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.PO_LINEITEM)
                    {
                        <tr>
                            <td>@item.ITEM.VendorItemID</td>
                            <td>@item.ITEM.Name</td>
                            <td>@item.QtyOrdered</td>
                            <td>@String.Format("{0:$0.00}", item.WholesaleCost)</td>
                            <td>@(String.Format("{0:$0.00}", item.QtyOrdered * item.WholesaleCost))</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="edit-line-items">
            <center>
                <input type="button" value="Edit Line Items" class="button"
                            onclick="location.href='@Url.Action("AddPOLineItem", "PurchaseOrder", 
                                        new {id = Model.POID})'" />
            </center>
        </div>
    </div>
</div>
<script>
    $('.datepicker').each(function () {
        $(this).datepicker();
    });
</script>

Warehouse/RecOutletWarehouse/RecOutletWarehouse/Views/PurchaseOrder/POLineItemListPart.cshtml
@model IEnumerable<RecOutletWarehouse.Models.PO_LINEITEM>
@* Partial View Listing the Purchase Order Line Items *@

@if (Model.ToList().Count == 0 ) {
<div>No items have been added to this purchase order yet. Use the item listing below to add items.</div>
}
else{
<table >
    <tr class="leftjust">
        <th>Item Name</th>
        <th>Vendor Item #</th>
        <th>Qty Ordered</th>
        <th>Cost Each</th>
        <th>Cost All</th>
    </tr>


    @foreach (var item in Model) {
        <tr>
                @using (Ajax.BeginForm("removeItemFromLineItems", new AjaxOptions { UpdateTargetId = "currentLines" })) {
                    
                    <td>@Html.DisplayFor(modelItem => item.ITEM.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.ITEM.VendorItemID)</td>
                    <td>@Html.DisplayFor(modelItem => item.QtyOrdered)</td>
                    <td>$@Html.DisplayFor(modelItem => item.WholesaleCost)</td>
                    <td>@(String.Format("{0:$0.00}", item.WholesaleCost * item.QtyOrdered))</td>
                    <td>
                        <input type="hidden" name="lineItemID" value="@item.POLineItemID" />
                        <input type="submit" value="Remove Item" class="button" />
                    </td>
                }
            
        </tr>
    }
    <tr class="sumrow">
        <td colspan ="3"></td>
        <td>TOTAL</td>
        <td colspan="2">
            @ViewBag.TotalPOCost
        </td>
    </tr>
</table>
}

Warehouse/RecOutletWarehouse/RecOutletWarehouse/Views/PurchaseOrder/SearchPO.cshtml
@using RecOutletWarehouse.HtmlHelpers;
@model RecOutletWarehouse.Controllers.PurchaseOrderController.PurchaseOrderSearchViewModel
@{
    ViewBag.Title = "Browse Purchase Orders";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section tabnavigation{
    <ul class="nav clearfix">
        <li>@Html.ActionLink("Create New PO","CreateNewPO")</li>
        <li class="active">@Html.ActionLink("Browse/Search POs","SearchPO")</li>
    </ul>  
}
<h2>Browse / Search Purchase Orders</h2>
<h3>Search</h3>
@using (Html.BeginForm())
{
    <div class="search">
        PO's Order Date: @Html.TextBox("orderDate", DateTime.Now.ToString("MM/dd/yyyy"), new { @class = "datepicker" })
        <input type="submit" value="Search" />
    </div>
}
<hr />
<div class="center-element center-text potable-area">
    <table class="potable" id="potable">
        <thead>
            <tr>
                <th>ID</th>
                <th>Order Date</th>
                <th>Estimated Ship Date</th>
                <th>Odered By</th>
                <th>Freight Cost</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.POs)
            {
                 <tr>
                    <td>@Html.DisplayFor(x => item.POID)</td>
                    <td>@Html.DisplayFor(x => item.POOrderDate, "ShortDateTime")</td>
                    <td>@Html.DisplayFor(x => item.POEstimatedShipDate)</td>
                    <td>@Html.DisplayFor(x => item.EMPLOYEE.FirstName) @Html.DisplayFor(x => item.EMPLOYEE.LastName)</td>
                    <td>@Html.DisplayFor(x => item.POFreightCost)</td>
                    <td><input type="button" value="Edit" class="button"
                                                            onclick="location.href='@Url.Action("EditPO", "PurchaseOrder", 
                                                                        new {id = item.POID})'" /></td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="searchTotal">@Model.PagingInfo.TotalItems Purchase Orders match current sorting criteria</div>
<div class="pager">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("SearchPO", new { page = x }))
</div>
<script>
    $('.datepicker').each(function () {
        $(this).datepicker();
    });
</script>
