Warehouse/RecOutletWarehouse/RecOutletWarehouse/Controllers/ReceivingLogController.cs
using RecOutletWarehouse.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RecOutletWarehouse.Utilities;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.ComponentModel.DataAnnotations;

namespace RecOutletWarehouse.Controllers
{
    public class ReceivingLogController : Controller
    {
        public RecreationOutletContext db = new RecreationOutletContext();
        public int BrowsePageSize = 25; // The number of results we want to show on each BrowseVendor page

        public class ReceivingLogCreationViewModel
        {
            //public List<RecOutletWarehouse.Models.RECEIVING_LOG> RL { get; set; }
            public List<RECEIVING_LOG> RL { get; set; }
            //public List<RecOutletWarehouse.Models.PurchaseOrder.PurchaseOrderLineItem> LineItems { get; set; }
            public List<PO_LINEITEM> LineItems { get; set; }
        }

        public class BrowseReceivingLogViewModel
        {
            public IEnumerable<RECEIVING_LOG> RLs { get; set; }
            public PagingInfo PagingInfo { get; set; }
            public string search { get; set; }
            public string startLetter { get; set; }
        }

        //
        // GET: /ReceivingLog/

        public ActionResult Index()
        {
            try
            {
                //DataFetcherSetter dbfs = new DataFetcherSetter();

                //List<RecOutletWarehouse.Models.PurchaseOrder.PurchaseOrder> objItem = new List<RecOutletWarehouse.Models.PurchaseOrder.PurchaseOrder>();

                return GetNonReceivedPOs();
                //return View();
            }
            catch (Exception ex)
            {
                WarehouseUtilities.LogError(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult GetNonReceivedPOs()
        {
            List<PURCHASE_ORDER> objItem = new List<PURCHASE_ORDER>();

            //Why does the LineItem portion come back null?
            //objItem = dbfs.GetNonReceivedPOs();

            //from s in db.Services
            //join sa in db.ServiceAssignments on s.Id equals sa.ServiceId
            //where sa.LocationId == 1
            //select s

            //var pre = (from P in db.PURCHASE_ORDER
            //           join PL in db.PO_LINEITEM on P.POID equals PL.POID
            //           join RL in db.RECEIVING_LOG on PL.POLineItemID equals RL.POLineItemID
            //           where PL.QtyOrdered == RL.ReceivedQty
            //           select P).Distinct();

            var cte = (from P in db.PURCHASE_ORDER
                       //List<PURCHASE_ORDER> cte = (from P in db.PURCHASE_ORDER
                       join PL in db.PO_LINEITEM on P.POID equals PL.POID
                       //join RL in db.RECEIVING_LOG on PL.POLineItemID equals RL.POLineItemID
                       //join RL in db.RECEIVING_LOG.DefaultIfEmpty() on PL.POLineItemID equals RL.POLineItemID
                       join RL in db.RECEIVING_LOG on PL.POLineItemID equals RL.POLineItemID
                       where PL.QtyOrdered == RL.ReceivedQty
                       //where RL.ReceivingID.Equals(null)
                       //where RL.ReceivingID == null
                       //where P.POID not in pre(x=> x.
                       select P).Distinct();//.ToList().OrderBy(P=>P.POOrderDate);
            //.ToList<PURCHASE_ORDER>();

            //Shouldn't be necessary as all POs should have at least 1 line item.
            var temp = (from P in db.PURCHASE_ORDER
                        join PL in db.PO_LINEITEM on P.POID equals PL.POID
                        select P).Distinct();

            //.Where(e => !hasFacilities.Any(m => m.FacilityId == e.FacilityId))
            //objItem = db.PURCHASE_ORDER.Where(x => !cte.Any(m => m.POID == x.POID)).Take(50).ToList();
            //COMPLETE THIS QUERY
            //objItem = db.PURCHASE_ORDER.Take(50).ToList();
            //objItem = cte;
            // objItem = db.PURCHASE_ORDER.Where(x => x.POID == cte.All(m => m.POID));
            //objItem = db.PURCHASE_ORDER.Where(x => 
            //objItem = cte.OrderBy(P => P.POOrderDate).Take(50).ToList<PURCHASE_ORDER>();//.OrderBy(P => P.POOrderDate).Take(50);
            objItem = db.PURCHASE_ORDER.Where(x => !cte.Any(m => m.POID == x.POID) && temp.Any(n => n.POID == x.POID)).OrderBy(p => p.POOrderDate).Take(50).ToList();

            ViewBag.NonReceivedPOs = objItem;

            return View("Index");
        }

        //
        // GET: /ReceivingLog/Details/5

        public ActionResult Details(int id)
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                WarehouseUtilities.LogError(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        //
        // GET: /ReceivingLog/Create
        //IS THIS EVEN USED? ------------------------------------------------
        //public ActionResult Create()
        //public ActionResult CreateNewRL()
        //{
        //    try
        //    {
        //        DataFetcherSetter dbfs = new DataFetcherSetter();

        //        //List<RecOutletWarehouse.Models.PurchaseOrder.PurchaseOrder> objItem = new List<RecOutletWarehouse.Models.PurchaseOrder.PurchaseOrder>();
        //        List<PURCHASE_ORDER> objItem = new List<PURCHASE_ORDER>();

        //        //Why does the LineItem portion come back null?
        //        //objItem = dbfs.GetNonReceivedPOs();

        //        var cte = (from P in db.PURCHASE_ORDER
        //                   join PL in db.PO_LINEITEM on P.POID equals PL.POID
        //                   join RL in db.RECEIVING_LOG on PL.POLineItemID equals RL.POLineItemID
        //                   where PL.QtyOrdered == RL.ReceivedQty
        //                   select P).ToList();
        //        //.Where(e => !hasFacilities.Any(m => m.FacilityId == e.FacilityId))
        //        //objItem = db.PURCHASE_ORDER.Where(x => !cte.Any(m => m.POID == x.POID)).Take(50).ToList();
        //        //COMPLETE THIS QUERY
        //        objItem = db.PURCHASE_ORDER.Take(50).ToList();

        //        ViewBag.NonReceivedPOs = objItem;

        //        //return View();
        //        return View("Index");
        //    }
        //    catch (Exception ex)
        //    {
        //        WarehouseUtilities.LogError(ex);
        //        return RedirectToAction("Error", "Home");
        //    }
        //}

        //
        // POST: /ReceivingLog/Create

        //[HttpPost]
        ////public ActionResult Create(ReceivingLog RL)
        //public ActionResult CreateNewRL(RECEIVING_LOG RL)
        ////public ActionResult Index(ReceivingLog RL)
        //{
        //    //try
        //    //{
        //    //    // TODO: Add insert logic here

        //    //    return RedirectToAction("Index");
        //    //}
        //    //catch
        //    //{
        //    //    return View();
        //    //}
        //    try
        //    {
        //        if (!ModelState.IsValid)
        //        {
        //            //return View(RL);
        //            //return View("Index", RL);
        //            return View("Index");
        //        }
        //        else
        //        {
        //            //DataFetcherSetter db = new DataFetcherSetter();

        //            //db.NewReceivingLog(//RL.ReceivingID,
        //            //    RL.POLineItemID, RL.BackorderID,
        //            //    RL.QtyTypeID, RL.ReceiveDate,
        //            //    RL.ReceivingNotes, RL.ReceivedQty);

        //            db.RECEIVING_LOG.Add(RL);
        //            db.SaveChanges();

        //            //return View("CreateNewRL");
        //            return View("Index");
        //            //return View(RL);
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        WarehouseUtilities.LogError(ex);
        //        return RedirectToAction("Error", "Home");
        //    }
        //}

        //
        // GET: /ReceivingLog/Edit/5

        public ActionResult EditRL(int id)
        {
            try
            {
                RECEIVING_LOG rl = db.RECEIVING_LOG.Where(x => x.ReceivingID == id).First();

                ViewBag.editRL = rl;

                return View();
            }
            catch (Exception ex)
            {
                WarehouseUtilities.LogError(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        //
        // POST: /ReceivingLog/Edit/5

        [HttpPost]
        //public ActionResult EditRL(int id, FormCollection collection)
        //public ActionResult EditRL(RECEIVING_LOG LOG)
            //apparently whatever model is chosen is passed back and forth between associated view
            //and controller call. so on post it passed back edited model. BUT THE MODEL HAS TO BE
            //IN THE CONTROLLER ORIGINALLY FOR IT TO SEE IT.
        public ActionResult EditRL(ReceivingLogCreationViewModel log)
        {
            try
            {
                // TODO: Add update logic here

                //enum error?
                //foreach (RECEIVING_LOG uprlog in log)
                //{
                //    db.RECEIVING_LOG.Attach(log.RL[0]);
                //    var entry = db.Entry(log.RL[0]);
                //    entry.Property(e => e.ReceivingID).IsModified = false;
                //    entry.Property(e => e.POLineItemID).IsModified = false;
                //if(

Warehouse/RecOutletWarehouse/RecOutletWarehouse/Views/ReceivingLog/BrowseReceivingLogs.cshtml
@*@using RecOutletWarehouse.HtmlHelpers;*@
@model RecOutletWarehouse.Controllers.ReceivingLogController.BrowseReceivingLogViewModel

@{
    ViewBag.Title = "SearchRL";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@section tabnavigation{
    <ul class="nav clearfix">
        <li>@Html.ActionLink("Create Receiving Log", "Index")</li>
        <li class="active">@Html.ActionLink("Browse Receiving Logs", "")</li>
    </ul>  
}

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

<script>
@*<script type="text/javascript">*@
    @*$(function () {
        $(".actionMenu").menu();
    });*@

    //$(function () {
    //    $("#accordion").accordion();
    //});
    //$('#togButton').click(function (id) {
    //$(function() {
    //    function togRow (id) {
    //        var effect = blind;
    //        var options = {};
    //        $('a\\'+id).toggle(effect, options, 400);
    //    }
    //});

    //function togglez(ID) {
    //    document.getElementById("a\\"+ID).
    //}
</script>

<h2>Browse and View Receiving Logs</h2>

@using (Html.BeginForm())
{
    <div class="search">
        PO's Order Date: @Html.TextBox("receiveDate", DateTime.Now.ToString("MM/dd/yyyy"), new { @class = "datepicker" })
        <input type="submit" value="Search" />
    </div>
}
<hr />
<div class="center-element center-text potable-area">
    <table class="potable" id="potable">
        <thead>
            <tr>
                <th>Receiving Log ID</th>
                <th>PO Line Item ID</th>
                <th>Received Date</th>
                <th>Quantity Type</th>
                <th>Received Quantity</th>
                <th>Receiving Log Notes</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.RLs)
            {
                @*<div id="accordion">
                    <h3>*@
                 <tr>
                     
                    <td>@Html.DisplayFor(x => item.ReceivingID)</td>
                    <td>@Html.DisplayFor(x => item.POLineItemID)</td>
                    <td>@Html.DisplayFor(x => item.ReceiveDate, "ShortDateTime")</td>
                    <td>@Html.DisplayFor(x => item.QtyTypeID)</td>
                    <td>@Html.DisplayFor(x => item.ReceivedQty)</td>
                    <td>@Html.DisplayFor(x => item.ReceivingNotes)</td>
                    <td><input type="button" class="button" 
                        onclick="JavaScript:newPopup('@Url.Action("EditRL", "ReceivingLog",
                        new { id = item.ReceivingID })');" 
                        value="Edit" /></td>
                     
                </tr>
                @*</h3>
                    <p>*@
               @* <tr id="a\@item.ReceivingID">
                    <td>hi</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>*@
                @* </p>
                </div>*@
            }
        </tbody>
    </table>
</div>
<script>
    $('.datepicker').each(function () {
        $(this).datepicker();
    });
</script>
<script type="text/javascript">
    function newPopup(url) {
        popupWindow = window.open(
            url, 'popUpWindow', 'height=700,width=1000,left=10,top=10,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no,status=yes')
    }
</script>


Warehouse/RecOutletWarehouse/RecOutletWarehouse/Views/ReceivingLog/EditRL.cshtml
@*model RecOutletWarehouse.Models.RECEIVING_LOG*@
@model RecOutletWarehouse.Controllers.ReceivingLogController.ReceivingLogCreationViewModel

@{
    ViewBag.Title = "EditRL";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<style>
.potable {
    height: 50px;
}
</style>

<h2 class="center-element center-text">EditRL</h2>

<br />

<div class="center-element center-text">
   

                  @using (Html.BeginForm("EditRL", "ReceivingLog", FormMethod.Post))
    {
        //<fieldset>
            <div class="potable-area">

            <table class="potable" id="RLtable">

                <tr>
                    <td colspan="6">
                        Current RL:
                        @ViewBag.editRL.ReceivingID
                    </td>
                </tr>

              <tr>
                  <th></th>
                  <th></th>
                <th>Item RPC:</th>
               @* <th>Qty Ordered:</th>*@
                <th>Qty Type ID:</th>
                <th>Receive Date:</th>
                <th>Qty Received:</th>
                <th>Notes:</th>
                @*<th></th>*@
              </tr>

            <tr>   

                <td>    
                @Html.HiddenFor(model => model.RL[0].ReceivingID, new { @Value = @ViewBag.editRL.ReceivingID })
                </td>
                <td>
                    @Html.HiddenFor(model => model.RL[0].PO_LINEITEM, new { @Value = @ViewBag.editRL.PO_LINEITEM })
                </td>

                <td>
                    @*Item RPC: *@
                    @ViewBag.editRL.POLineItemID
                    @Html.HiddenFor(model => model.RL[0].POLineItemID, new { @Value = @ViewBag.editRL.POLineItemID })
                </td>

                @*<td>
                    @ViewBag.editRL.ReceivedQty
                </td>*@
                <td>
                    @*Qty Type ID: *@
                    @*@objPO.QtyTypeId*@
                    @Html.HiddenFor(model => model.RL[0].QtyTypeID, new { @Value = @ViewBag.editRL.QtyTypeID })
                    @*FOR NOW: HARDCODED. later options will be retrieved from the db and will be dynamically added.*@
                    <select>
                        <option selected>1 - Each</option>
                        <option>2 - Case</option>
                        <option>3 - Pallet</option>
                    </select>
                    
                </td>
                <td>
                    @*Receive Date:*@ 
                    @Html.TextBoxFor(model => model.RL[0].ReceiveDate, new { type = "date", @Value = @ViewBag.editRL.ReceiveDate})
                    @*Html.TextBox("ReceiveDate", DateTime.Now, new { type = "date" })*@
                    @Html.ValidationMessageFor(model => model.RL[0].ReceiveDate)
                </td>
                <td>
                    @*Qty Received:*@ 
                    @Html.TextBoxFor(model => model.RL[0].ReceivedQty, new { @Value = @ViewBag.editRL.ReceivedQty })
                    @Html.ValidationMessageFor(model => model.RL[0].ReceivedQty)
                </td>
                <td>
                    @*Notes:*@ 
                    @Html.TextAreaFor(model => model.RL[0].ReceivingNotes, new { @Value = @ViewBag.editRL.ReceivingNotes })
                </td>
                @*<td><input type="submit" value="Record Received" /></td>*@
            </tr>
            
           @*RecOutletWarehouse.Models.PurchaseOrder.PurchaseOrderLineItem item = objItem;*@


            </table>
        </div>
           // </fieldset>
                  
       

        <br />
            @*Html.Hidden("count", count)*@
            <input type="submit" value="Update Log" class="button" />
}
         
    </div>
       
    

Warehouse/RecOutletWarehouse/RecOutletWarehouse/Views/ReceivingLog/Index.cshtml
@model RecOutletWarehouse.Controllers.ReceivingLogController.ReceivingLogCreationViewModel

@{
    ViewBag.Title = "Create Receiving Log";
    //ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@section tabnavigation{
    <ul class="nav clearfix">
        <li class="active">@Html.ActionLink("Create Receiving Log", "Index")</li>
        <li>@Html.ActionLink("Browse Receiving Logs", "BrowseReceivingLogs")</li>
    </ul>  
}

@*submitForms = function(){*@

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">
<!-- Data Table Stuffs? -->
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
<link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">
<style>
    #feedback { font-size: 1.4em; }
    #selectable .ui-selecting { background: #FECA40; }
    #selectable .ui-selected { background: #F39814; color: white; }
    #selectable { list-style-type: none; margin: 0; padding: 0; width: 60%; }
    #selectable li { margin: 3px; padding: 0.4em; font-size: 1.4em; height: 18px; }
</style>
@*<script type ="text/javascript">*@
<script>
    $(function () {
        $("#selectable").selectable({ selected: function (event, ui) { } })
    });

    $(document).ready(function () {
        $("#potable").dataTable();
    });

    $(function () {
        $("#selectable").on("selectableselected", function (event, ui) {
            //$("#po").val($("#selectable").index(event.currentTarget).text());
            //$("#po").val(event.currentTarget.innerText);
            $("#po").val($("#selectable").text());
            //$("#po").text("hello")
            //$("po").html("hello");
            //alert("hello");
            //var poText = $("po").text();
            //var poText = $("#po").val();
            //alert(poText);
        })
    });

    //$(function () {
    //    $("#po").val(
    //});

    $(function () {
        $("#recDate").datepicker();
    });
</script>
<script type="text/javascript">
    //function fillPOwithID()
    //{
    //    document.getElementById("po").value();
    //}

    function fillPOwithID(ID) {
        //alert(ID);
        document.getElementById("po").value = ID;
        document.forms["orig"].submit();
        //document.forms["origForm"].submit();
        //document.orig.submit();
        //document.origForm.submit();
        //document.getElementById("orig").submit();
        //document.getElementsByName("origForm").submit();
        //document.getElementById("po").submit();
        //alert("submit?");
        //document.getElementById("poSub").submit();
    }
</script>

<h2>Create Receiving Log</h2>
<div class="center-element center-text">
    <table class="button-columns">
        <tr>
            @*<td><input type="button" value="Create New Receiving Log" class="main-menu-button"
                onclick="location.href='@Url.Action("CreateNewRL","ReceivingLog")'" /></td>
            <td><input type="button" value="Search for Receiving Log" class="main-menu-button"
                onclick="location.href='@Url.Action("Search","ReceivingLog")'" /></td>*@

            @*<select name="FavWebSite" size="5">
                <option value="SM">http://www.scriptingmaster.com</option>
                <option value="Google">http://www.google.com</option>
                <option value="MSN">http://www.msn.com</option>
                <option value="yahoo">http://www.yahoo.com</option>
                <option value="microsoft">http://www.microsoft.com</option>
            </select>*@

            

        </tr>
    </table>

    @*PO ID:*@
    
    @*using (Html.BeginForm("findPO", "RECEIVING_LOG", new { name = "origForm", id = "orig" }))*@
    @*using (Html.BeginForm("findPO", "ReceivingLogController", new { name = "origForm", id = "orig" }))*@
    @*@using (Html.BeginForm("findPO", "ReceivingLog", new { name = "origForm", id = "orig" }))*@
    
    @*@using (Html.BeginForm("findPO", "ReceivingLog", FormMethod.Post, new { name = "origForm", id = "orig" }))
    {
        <input type="text" placeholder="" id="po" name="po" />          
        //<input type="text" id="po" />
        <input type="submit" value="Begin RL" class="button" id="poSub"/>
    }

    <br />*@


@if (Model != null)
{
    //ReceivingLogCreationViewModel
    //var count = 1;
    var count = 0;

    //using (Html.BeginForm("MarkedReceived", "ReceivingLog"))//, FormMethod.Post)) //, new { name = count + "", id = count + "", onsubmit = "return false;"}) )
    //using (Html.BeginForm("CreateReceived", "ReceivingLog"))//, FormMethod.Post)) //, new { name = count + "", id = count + "", onsubmit = "return false;"}) )

    using (Html.BeginForm("CreateReceived", "ReceivingLog", FormMethod.Post))//, new { name = count + "", id = count + "", onsubmit = "return false;"}) )
    //using (Html.BeginForm("CreateReceived", "RECEIVING_LOG", FormMethod.Post))//, new { name = count + "", id = count + "", onsubmit = "return false;"}) )

    //using (Html.BeginForm("CreateReceived", "ReceivingLogController", FormMethod.Post))//, new { name = count + "", id = count + "", onsubmit = "return false;"}) )
    //CreateReceived
    //using(Html.BeginForm())
    {
        <div class="center-element center-text potable-area">
            <table class="potable" id="RLtable">

                <tr>
                    <td colspan="6">
                        Current PO:
                        @ViewBag.CurrentPO
                    </td>
                </tr>

              <tr>
                <th>Item RPC:</th>
                <th>Qty Ordered:</th>
                <th>Qty Type ID:</th>
                <th>Receive Date:</th>
                <th>Qty Received:</th>
                <th>Notes:</th>
                @*<th></th>*@
              </tr>

            @*foreach (RecOutletWarehouse.Models.PurchaseOrder.PurchaseOrderLineItem objPO in Model.LineItems)*@
            @foreach (RecOutletWarehouse.Models.PO_LINEITEM objPO in Model.LineItems)
            {
            
            <tr>    @*Modify tr attributes to have padding and hold the border. Remove border from td*@
                
                @*However, due to the fact these are commented out, null data is being put in*@
                @*<td>
                    PO Line Item:
                    @objPO.POLineItem
                    @Html.HiddenFor(model => model.RL[count].POLineItemID, new { @Value = @objPO.POLineItem })
                </td>*@
                @*<td>
                    Purchase Order: @objPO.POID
                    //{ViewBag.POID = @objPO.POID;}
                    @Html.Hidden("POID", @objPO.POID)
                </td>*@

                @Html.Hidden("POID", @objPO.POID)
                @Html.HiddenFor(model => model.RL[count].POLineItemID, new { @Value = @objPO.POLineItemID })
                
                <td>
                    @*Item RPC: *@
                    @objPO.RecRPC
                </td>
                <td>
                    @*Qty Ordered: *@
                    @objPO.QtyOrdered
                </td>
                <td>
                    @*Qty Type ID: *@
                    @*@objPO.QtyTypeId*@
                    @Html.HiddenFor(model => model.RL[count].QtyTypeID, new { @Value = @objPO.QtyTypeID })
                    @*FOR NOW: HARDCODED. later options will be retrieved from the db and will be dynamically added.*@
                    <select>
                        <option selected>1 - Each</option>
                        <option>2 - Case</option>
                        <option>3 - Pallet</option>
                    </select>
                    
                </td>
                <td>
                    @*Receive Date:*@ 
                    @Html.TextBoxFor(model => model.RL[count].ReceiveDate, new { type = "date", @Value = DateTime.Now.Date.ToString("MM/dd/yyyy"), id = "recDate" })
                    @*Html.TextBox("ReceiveDate", DateTime.Now, new { type = "date" })*@
                    @Html.ValidationMessageFor(model => model.RL[count].ReceiveDate)
                </td>
                <td>
                    @*Qty Received:*@ 
                    @Html.TextBoxFor(model => model.RL[count].ReceivedQty, new { @Value = @objPO.QtyOrdered })
                    @Html.ValidationMessageFor(model => model.RL[count].ReceivedQty)
                </td>
                <td>
                    @*Notes:*@ 
                    @Html.TextAreaFor(model => model.RL[count].ReceivingNotes)
                </td>
                @*<td><input type="submit" value="Record Received" /></td>*@
            </tr>
            
           @*RecOutletWarehouse.Models.PurchaseOrder.PurchaseOrderLineItem item = objItem;*@
            
                count++;

            }

            </table>

        </div>
    
        <br />
            @*Html.Hidden("count", count)*@
            <input type="submit" value="Record Received" class="button" />
    
    }

        @*}*@

    @*</table>*@

        @*<input type="button" value="Record Received" onclick="submitForms(1)" />*@
 
    //}
    //}


}

@if (ViewBag.NonReceivedPOs != null)
{
    //PO ID:
    //@
    using (Html.BeginForm("findPO", "ReceivingLog", FormMethod.Post, new { name = "origForm", id = "orig" }))
    {
        <input type="text" placeholder="Search by PO ID" id="po" name="po" />          
        //<input type="text" id="po" />
        <input type="submit" value="Begin RL" class="button" id="poSub"/>
    }

    <br />
    
   @* <ol id="selectable">
            
            @foreach (RecOutletWarehouse.Models.PurchaseOrder.PurchaseOrder objPO in ViewBag.NonReceivedPOs)
            {
            
            <li class="ui-widget-content">
                PO Line Item:
                @objPO.PurchaseOrderId
            </li>

            }

        </ol>
    *@
    
    <table id="potable">
        <thead>
            <tr>
                <th>PO ID:</th>
                <th>Est Ship Date:</th>
                <th>Order Date:</th>
                <th>Vendor:</th>
                @*<th>Created By:</th>*@
                <th>Comments:</th>
            </tr>
        </thead>

        <tbody>
            @*foreach (RecOutletWarehouse.Models.PurchaseOrder.PurchaseOrder objPO in ViewBag.NonReceivedPOs)*@
            @foreach (RecOutletWarehouse.Models.PURCHASE_ORDER objPO in ViewBag.NonReceivedPOs)
            {
            
            <tr>
                <td><a href="javascript:fillPOwithID(@objPO.POID)">@objPO.POID</a></td>
                <td>@objPO.POEstimatedShipDate</td>
                <td>@objPO.POOrderDate</td>
                <td>@objPO.VendorID</td>
                @*<td>@objPO.CreatedBy</td>*@
                <td>@objPO.POComments</td>
            </tr>

            }

        </tbody>

    </table>
    
}

<br />

    

</div>